### ISSUE TITLE
Show Timed Out Requests

### ISSUE THREAD

**Issue by ngkogkos** [nccgroup/AutoRepeater#24]
Can you please look into handling requests that time out? 

This could be done in the same manner Burp's history time displays an empty response tab, and even be flagged. From my testing it seems to be a quite often thing due to WAFs etc.

**Comment by justinmoore** [comment]
Hey @ngkogkos,

I agree that this would be a good feature. Unfortunately, Burp's API doesn't provide an easy way to implement this because it doesn't tie outgoing requests to their incoming responses. I've looked at how both Flow and Logger++ implement this functionality and I don't think either of them do it in a great way.

Logger++ only tracks requests without responses for requests that go through Burp's proxy which does assign them a unique identifier to track. It looks like Flow iterates over an ArrayList whenever a response is received to match the incoming response to the sent request. 

I think this is doable in a way that doesn't add excessive overhead by using something like a HashMap to track out going requests and having a worker in a different thread periodically iterate over all the keys in the HashMap to removed timed out entires.

I'm going to stew on this for a bit before implementing the feature to make sure I do it in a way that doesn't add too much complexity or overheard.

thanks,
Justin

**Comment by ngkogkos** [comment]
That sounds reasonable to me. Sorry I cannot contribute but I don't get along with Java.

Anyhow it's a great idea for a plugin and very useful already :)

**Comment by justinmoore** [comment]
This should work now.

Thanks,
Justin
